name: Update gist with Code::Stats stats
on:
  push:
    branches:
      - master
      - reenable-workflow
  schedule:
    - cron: "0 */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python codestats_box.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b163c0bdbc70b6e8a4bb3413d634a1b1
          CODE_STATS_USERNAME: nescap
          STATS_TYPE: recent-xp
